server:
  port: 8282

resource:
  url: http://localhost:8484

spring:
  security:
    oauth2:
      client:
        registration:
          myoauth2:
            provider: spring
            client-id: client
            client-secret: secret
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8282/login/oauth2/code/myoauth2
        provider:
          spring:
            issuer-uri: http://localhost:8989

